const dogTaglines = [
  "The Treats Detective",
  "Barking Up the Right Tree",
  "Pawsitively Adorable",
  "Fetching Hearts Everywhere",
  "Leading the Pack",
  "Sniffing Out Adventure",
  "The Ultimate Lap Dog",
  "Tail Wagging Champion",
  "Dreaming of Treats",
  "Squirrel Patrol Specialist",
  "Canine Connoisseur",
  "The Backyard Explorer",
  "The Bark Knight Rises",
  "Woofer of Wall Street",
  "Cuddle Champion at Large",
  "Paws and Reflect",
  "Four-Legged Love Machine",
  "Sofa Surfing Specialist",
  "Professional Hole Digger",
  "Master of Tail Wags",
  "Snuggle Bug Extraordinaire",
  "The Fast and the Furriest",
  "Furball of the Opera",
  "Pup-casso of Paw Painting",
  "Hairy Paw-ter and the Sorcerer Bone",
  "Bark Twain, the Literary Genius",
  "Captain of the Chew Toy",
  "The Woof on Wall Street",
  "Sir Barks-a-Lot",
  "Drool Sergeant in Command",
  "Guardian of the Food Bowl",
  "Nap Enthusiast and Dream Chaser",
  "The Unofficial Neighborhood Watch",
  "Escape Artist Extraordinaire",
  "Squirrel Surveillance Squad",
  "Chief of Treat Negotiations",
  "Adventures in Bark-sniffing",
  "Mischief Manager",
  "The Fluffiest Cloud on Four Legs",
  "Beach Sand Connoisseur",
  "Supreme Ruler of the Fetch Field",
  "The Legendary Leash Escape Artist",
  "Explorer of Uncharted Sofas",
  "Couch Potato Critic",
  "The Sniff Whisperer",
  "Mud Puddle Aficionado",
  "The Zen Master of Barks",
  "Junk Food Detective",
  "Sunbeam Collector",
  "Treats Analyst",
  "Chief Executive Snuggler",
  "Ball Fetching CEO",
  "Resident Barkitect",
  "Doctor Woof, the Time Traveler",
  "Agent Fluffy Butt on Duty",
  "Pawfessional Heart Stealer",
  "The Furrminator",
  "Dreamy Paws of Comfort",
  "The Howling Philosopher",
  "Circuit Breaker of Hearts",
  "Grand Poo-bah of the Porch Patrol",
  "Sir Waggington of the Round Table",
  "The pillow destroyer",
];

export default dogTaglines;
